export const blogs = [
  { cat: "Éducation", title: "Upendo Feast : Distribution de kits scolaires", excerpt: "À l'occasion de la Journée internationale de l'enfant africain, nous avons distribué des kits scolaires aux enfants de l'E.P. Bukunda dans la chefferie de MITI.", date: "20 juin 2024", img: "/component_pictures/blog/20_juin_2024.jpeg" },
  { cat: "Organisation", title: "1ère Assemblée Générale : Bâtir l'avenir ensemble", excerpt: "Réunion des membres internes et externes pour définir les orientations stratégiques et renforcer la cohésion de l'organisation.", date: "6 juillet 2024", img: "/component_pictures/blog/6_juillet_2024.png" },
  { cat: "Organisation", title: "Deuxième Assemblée Générale", excerpt: "Présentation et évaluation de la deuxième édition du projet annuel Upendo Feast. Les échanges ont porté sur l'écoute, l'empathie, la sensibilisation et le parrainage des enfants vulnérables, ainsi que sur les améliorations futures du projet.", date: "25 juin 2025", img: "/component_pictures/blog/25_juin_2025.jpeg" },
  { cat: "Santé", title: "Hygiène Menstruelle : Briser le silence en milieu rural", excerpt: "Séances de sensibilisation à l'hygiène menstruelle pour les jeunes filles de MITI, avec distribution de kits hygiéniques.", date: "5 août 2025", img: "/component_pictures/blog/5_aout_2025.jpeg" },
  { cat: "Social", title: "Activité « Arbre de Vie » — AFPD Bukavu", excerpt: "Séance d'écoute et d'empathie avec les enfants du centre de l'AFPD à Nguba. Espace sécurisé pour partager rêves et aspirations.", date: "30 août 2025", img: "/component_pictures/blog/30_aout_2025.png" },
  { cat: "Éducation", title: "Journée de l'Éducation : Anglais et e-books", excerpt: "Apprentissage de l'anglais et distribution d'e-books aux enfants de l'AFPD pour renforcer leur encadrement éducatif.", date: "24 janvier 2026", img: "/component_pictures/blog/24_janvier_2026.jpeg" },
  { cat: "Agriculture", title: "Ouverture officielle Commission Agri-Business", excerpt: "Lancement de la commission d'agri-business pour promouvoir la santé nutritionnelle et l'entrepreneuriat communautaire.", date: "24 février 2026", img: "/component_pictures/blog/24_fevrier_2026.jpeg" },
];
