export type TeamMember = {
  id?: string;
  nom: string;
  poste: string;
  bio: string;
  photo_url: string;
  ordre: number;
  actif: boolean;
};

export const DEFAULT_TEAM_MEMBERS: TeamMember[] = [
  { nom: 'BYAMUNGU Cinyunyi David', poste: 'Fondateur & Président du CA', bio: "Titulaire d'une licence en droit de l'Université Officielle de Bukavu (UOB) et boursier du Gouvernement australien en Humanity Community Service, il incarne un leadership fondé sur le service, la justice et l'innovation sociale. Son engagement vise à mobiliser les communautés, défendre les droits de l'enfant et promouvoir des initiatives durables.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/byamungu-cinyunyi-david.jpg', ordre: 0, actif: true },
  { nom: 'Georges Cinyunyi', poste: 'Co-fondateur', bio: "Acteur humanitaire d'expérience avec plus de 20 ans passés au sein de la FAO (Nations Unies). Il transforme aujourd'hui ce riche parcours en un héritage puissant pour la fondation.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/georges.jpeg', ordre: 1, actif: true },
  { nom: 'Rachel Nab', poste: 'External Relations Officer', bio: "Militante engagée dans le service communautaire, elle possède une expérience au sein d'Anglicare Australia. Passionnée par l'impact social, elle met ses compétences en communication et en relations extérieures au service de l'organisation.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/rachel.jpeg', ordre: 2, actif: true },
  { nom: 'Evelyne Kitumaini', poste: 'Défenseure des Droits Humains', bio: "Forte d'une expérience au sein de Family First en Ouganda, elle place l'épanouissement de l'enfant au cœur de toutes les initiatives de développement.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/evelyne.jpeg', ordre: 3, actif: true },
  { nom: 'Nelly Walubambo', poste: 'Coordinatrice Régionale & Genre', bio: "Juriste et activiste engagée, elle préside la commission du genre et milite ardemment pour l'égalité et la stricte application des droits de l'enfant.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/nelly.jpeg', ordre: 4, actif: true },
  { nom: 'Mugoli Musese Caroline', poste: 'Présidente Commission Santé', bio: "Détentrice d'une licence en santé publique (UOB), elle déploie avec compassion son expertise pour garantir le bien-être sanitaire des enfants vulnérables.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/caroline.jpeg', ordre: 5, actif: true },
  { nom: 'Salama Bagalwa Mireille', poste: 'Présidente Agri-business', bio: "Licenciée en agro-industrie (UEA), elle allie transformation agro-alimentaire et sécurité nutritionnelle pour soutenir la santé infantile.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/mireille.jpeg', ordre: 6, actif: true },
  { nom: 'Josué Ntaboba Cubaka', poste: 'Administration', bio: "Titulaire d'un Master en Droit de l'UOB, il agit avec détermination pour doter l'organisation d'un cadre administratif rigoureux au service de l'action humanitaire.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/josue.jpeg', ordre: 7, actif: true },
  { nom: 'Murhula Maroy Pontien', poste: 'Activiste Humanitaire', bio: "Détenteur d'un Master en Droit (UOB), il participe activement et avec abnégation aux initiatives visant à secourir et protéger les plus vulnérables.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/pontien.jpeg', ordre: 8, actif: true },
  { nom: 'Daniella Marhegane', poste: "Membre du Conseil d'Administration", bio: "Originaire de Bukavu, elle se distingue par sa capacité d'écoute et son efficacité redoutable dans le déploiement opérationnel des activités de terrain.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/daniella.jpeg', ordre: 9, actif: true },
  { nom: 'Adolphe Bahige', poste: 'Expert IT & Humanitaire', bio: "Licencié en informatique de l'Université Espoir d'Afrique. Il met la puissance du numérique au profit de l'encadrement stratégique de nos actions.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/adolphe.jpeg', ordre: 10, actif: true },
  { nom: 'Kangewenye Nzigire Byeby', poste: 'Administration', bio: "Passionnée et organisée, elle s'investit avec humanisme et rigueur dans la gestion quotidienne de nos missions.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/byeby.jpeg', ordre: 11, actif: true },
  { nom: 'ATUMISSI LUGHOBYO AUBIN', poste: "Président Commission Éducation & Droits de l'enfant", bio: "Président de la Commission Éducation, Activités humanitaires et Défense des droits de l'enfant. Titulaire d'un Master en droit de l'Université Officielle de Bukavu (UOB), il met son expertise juridique au service de la protection des droits de l'enfant.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/aubin.jpeg', ordre: 12, actif: true },
  { nom: 'IRENGE RUSABUNGA Eric', poste: 'Responsable commission de justice', bio: "Chercheur en droit à l’université officielle de Bukavu, il incarne l’expertise, la rigueur et l’engagement pour la justice et œuvre à la promotion des droits de l'enfant et au renforcement de la protection juridique au sein de l’organisation.", photo_url: '/component_pictures/a_propos/membres_de_l_organisation/irenge.jpeg', ordre: 13, actif: true },
]; 
